/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EmailRouteImport } from './routes/email'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardWorkoutsRouteImport } from './routes/_dashboard/dashboard/workouts'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/_dashboard/dashboard/settings'
import { Route as DashboardDashboardOverviewRouteImport } from './routes/_dashboard/dashboard/overview'
import { Route as DashboardDashboardMealplannerRouteImport } from './routes/_dashboard/dashboard/mealplanner'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardWorkoutsRoute =
  DashboardDashboardWorkoutsRouteImport.update({
    id: '/dashboard/workouts',
    path: '/dashboard/workouts',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardOverviewRoute =
  DashboardDashboardOverviewRouteImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardMealplannerRoute =
  DashboardDashboardMealplannerRouteImport.update({
    id: '/dashboard/mealplanner',
    path: '/dashboard/mealplanner',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/email': typeof EmailRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/mealplanner': typeof DashboardDashboardMealplannerRoute
  '/dashboard/overview': typeof DashboardDashboardOverviewRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/workouts': typeof DashboardDashboardWorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/email': typeof EmailRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/mealplanner': typeof DashboardDashboardMealplannerRoute
  '/dashboard/overview': typeof DashboardDashboardOverviewRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/workouts': typeof DashboardDashboardWorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRoute
  '/email': typeof EmailRoute
  '/onboarding': typeof OnboardingRoute
  '/_dashboard/dashboard/mealplanner': typeof DashboardDashboardMealplannerRoute
  '/_dashboard/dashboard/overview': typeof DashboardDashboardOverviewRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/_dashboard/dashboard/workouts': typeof DashboardDashboardWorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/email'
    | '/onboarding'
    | '/dashboard/mealplanner'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/dashboard/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/email'
    | '/onboarding'
    | '/dashboard/mealplanner'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/dashboard/workouts'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/email'
    | '/onboarding'
    | '/_dashboard/dashboard/mealplanner'
    | '/_dashboard/dashboard/overview'
    | '/_dashboard/dashboard/settings'
    | '/_dashboard/dashboard/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthRoute: typeof AuthRoute
  EmailRoute: typeof EmailRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/workouts': {
      id: '/_dashboard/dashboard/workouts'
      path: '/dashboard/workouts'
      fullPath: '/dashboard/workouts'
      preLoaderRoute: typeof DashboardDashboardWorkoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/overview': {
      id: '/_dashboard/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardDashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/mealplanner': {
      id: '/_dashboard/dashboard/mealplanner'
      path: '/dashboard/mealplanner'
      fullPath: '/dashboard/mealplanner'
      preLoaderRoute: typeof DashboardDashboardMealplannerRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardMealplannerRoute: typeof DashboardDashboardMealplannerRoute
  DashboardDashboardOverviewRoute: typeof DashboardDashboardOverviewRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRoute
  DashboardDashboardWorkoutsRoute: typeof DashboardDashboardWorkoutsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardMealplannerRoute: DashboardDashboardMealplannerRoute,
  DashboardDashboardOverviewRoute: DashboardDashboardOverviewRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRoute,
  DashboardDashboardWorkoutsRoute: DashboardDashboardWorkoutsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthRoute: AuthRoute,
  EmailRoute: EmailRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
