#!/bin/sh

docker run -it \
  -e INFISICAL_ENV=$INFISICAL_ENV \
  -e INFISICAL_CLIENT_ID=$INFISICAL_CLIENT_ID \
  -e INFISICAL_CLIENT_SECRET=$INFISICAL_CLIENT_SECRET \
  -e INFISICAL_PROJECT_ID=$INFISICAL_PROJECT_ID \
  -e INFISICAL_DOMAIN=$INFISICAL_DOMAIN \
  nora-health $@
